C  FILE TO READ IN OBS. DATA FOR GATE.  FILES ARE ORGINALLY IN BINARY FORMAT

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      FUNCTION CVMGP(X1,X2,X3)
       IF(X3.GE.0.)  THEN
        CVMGP=X1
       ELSE
        CVMGP=x2
       ENDIF
      RETURN
      END
