CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE TIMING(T)
      !EXTERNAL ETIME         !sgi
      !REAL*4 ETIME,TARRAY(2) !sgi
      T=TIME()        !sgi
      RETURN
      END
