C
      SUBROUTINE WTAP_UV_S
      PARAMETER (NZ=43)
      real             SDIFF_VX(NZ,4),SDIFF_VZ(NZ,4),SGRID_VX(NZ,4),
     1                 SGRID_VZ(NZ,4),SDIFF_NV(NZ,4),SV_LARGE(NZ,4),
     2                 SPRE_V(NZ,4),SDT_V(NZ,4),TN_VWIND(NZ,4)
      COMMON/DEBUG_SV/ SDIFF_VX,SDIFF_VZ,SGRID_VX,
     1                 SGRID_VZ,SDIFF_NV,SV_LARGE,
     2                 SPRE_V,SDT_V,TN_VWIND

      real             SDIFF_UX(NZ,4),SDIFF_UZ(NZ,4),SGRID_UX(NZ,4),
     1                 SGRID_UZ(NZ,4),SDIFF_NU(NZ,4),SU_LARGE(NZ,4),
     2                 SPRE_U(NZ,4),SDT_U(NZ,4),TN_UWIND(NZ,4)
      COMMON/DEBUG_SU/ SDIFF_UX,SDIFF_UZ,SGRID_UX,
     1                 SGRID_UZ,SDIFF_NU,SU_LARGE,
     2                 SPRE_U,SDT_U,TN_UWIND

      real        UB_MEAN(NZ,4),VB_MEAN(NZ,4)
      COMMON/SUV/ UB_MEAN,VB_MEAN

      real             SSDIFF_VX(NZ,4),SSDIFF_VZ(NZ,4),SSGRID_VX(NZ,4),
     1                 SSGRID_VZ(NZ,4),SSDIFF_NV(NZ,4),SSV_LARGE(NZ,4),
     2                 SSPRE_V(NZ,4),SSDT_V(NZ,4),STN_VWIND(NZ,4)
      COMMON/DEBUG_SVS/ SSDIFF_VX,SSDIFF_VZ,SSGRID_VX,
     1                  SSGRID_VZ,SSDIFF_NV,SSV_LARGE,
     2                  SSPRE_V,SSDT_V,STN_VWIND

      real             SSDIFF_UX(NZ,4),SSDIFF_UZ(NZ,4),SSGRID_UX(NZ,4),
     1                 SSGRID_UZ(NZ,4),SSDIFF_NU(NZ,4),SSU_LARGE(NZ,4),
     2                 SSPRE_U(NZ,4),SSDT_U(NZ,4),STN_UWIND(NZ,4)
      COMMON/DEBUG_SUS/ SSDIFF_UX,SSDIFF_UZ,SSGRID_UX,
     1                  SSGRID_UZ,SSDIFF_NU,SSU_LARGE,
     2                  SSPRE_U,SSDT_U,STN_UWIND

      real        SUB_MEAN(NZ,4),SVB_MEAN(NZ,4)
      COMMON/SSUV/ SUB_MEAN,SVB_MEAN

C
      REAL BNZ4(NZ,4)
C
      CALL WTAP2 (SDIFF_VX,BNZ4,NZ,4,4)
      CALL WTAP2 (SDIFF_VZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SGRID_VX,BNZ4,NZ,4,4)
      CALL WTAP2 (SGRID_VZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SDIFF_NV,BNZ4,NZ,4,4)
      CALL WTAP2 (SV_LARGE,BNZ4,NZ,4,4)
      CALL WTAP2 (  SPRE_V,BNZ4,NZ,4,4)
      CALL WTAP2 (   SDT_V,BNZ4,NZ,4,4)
      CALL WTAP2 (TN_VWIND,BNZ4,NZ,4,4)
CCCCCC
      CALL WTAP2 (SDIFF_UX,BNZ4,NZ,4,4)
      CALL WTAP2 (SDIFF_UZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SGRID_UX,BNZ4,NZ,4,4)
      CALL WTAP2 (SGRID_UZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SDIFF_NU,BNZ4,NZ,4,4)
      CALL WTAP2 (SU_LARGE,BNZ4,NZ,4,4)
      CALL WTAP2 (  SPRE_U,BNZ4,NZ,4,4)
      CALL WTAP2 (   SDT_U,BNZ4,NZ,4,4)
      CALL WTAP2 (TN_UWIND,BNZ4,NZ,4,4)
cccccc
      CALL WTAP2 ( UB_MEAN,BNZ4,NZ,4,4)
      CALL WTAP2 ( VB_MEAN,BNZ4,NZ,4,4)
C
CC
C
      CALL WTAP2 (SSDIFF_VX,BNZ4,NZ,4,4)
      CALL WTAP2 (SSDIFF_VZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SSGRID_VX,BNZ4,NZ,4,4)
      CALL WTAP2 (SSGRID_VZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SSDIFF_NV,BNZ4,NZ,4,4)
      CALL WTAP2 (SSV_LARGE,BNZ4,NZ,4,4)
      CALL WTAP2 (  SSPRE_V,BNZ4,NZ,4,4)
      CALL WTAP2 (   SSDT_V,BNZ4,NZ,4,4)
      CALL WTAP2 (STN_VWIND,BNZ4,NZ,4,4)
CCCCCC
      CALL WTAP2 (SSDIFF_UX,BNZ4,NZ,4,4)
      CALL WTAP2 (SSDIFF_UZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SSGRID_UX,BNZ4,NZ,4,4)
      CALL WTAP2 (SSGRID_UZ,BNZ4,NZ,4,4)
      CALL WTAP2 (SSDIFF_NU,BNZ4,NZ,4,4)
      CALL WTAP2 (SSU_LARGE,BNZ4,NZ,4,4)
      CALL WTAP2 (  SSPRE_U,BNZ4,NZ,4,4)
      CALL WTAP2 (   SSDT_U,BNZ4,NZ,4,4)
      CALL WTAP2 (STN_UWIND,BNZ4,NZ,4,4)
cccccc
      CALL WTAP2 ( SUB_MEAN,BNZ4,NZ,4,4)
      CALL WTAP2 ( SVB_MEAN,BNZ4,NZ,4,4)
cccccc
C
      RETURN
      END
